/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gams_variables_Sensor */

#ifndef _Included_com_gams_variables_Sensor
#define _Included_com_gams_variables_Sensor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gams_variables_Sensor
 * Method:    jni_Sensor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_gams_variables_Sensor_jni_1Sensor__
  (JNIEnv *, jobject);

/*
 * Class:     com_gams_variables_Sensor
 * Method:    jni_Sensor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_gams_variables_Sensor_jni_1Sensor__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_variables_Sensor
 * Method:    jni_freeSensor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gams_variables_Sensor_jni_1freeSensor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gams_variables_Sensor
 * Method:    jni_getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gams_variables_Sensor_jni_1getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_variables_Sensor
 * Method:    jni_init
 * Signature: (JJJLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_gams_variables_Sensor_jni_1init
  (JNIEnv *, jobject, jlong, jlong, jlong, jstring, jdouble);

/*
 * Class:     com_gams_variables_Sensor
 * Method:    jni_toString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gams_variables_Sensor_jni_1toString
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
