/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "gams/GAMS_Export.h"
/* Header for class com_gams_platforms_VrepPlatform */

#ifndef _Included_com_gams_platforms_VrepPlatform
#define _Included_com_gams_platforms_VrepPlatform
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_gams_platforms_VrepPlatform
 * Method:    jni_simStart
 * Signature: (Ljava/lang/String;I)I
 */
GAMS_Export jint JNICALL Java_com_gams_platforms_VrepPlatform_jni_1simStart
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_gams_platforms_VrepPlatform
 * Method:    jni_addModelToEnvironment
 * Signature: (ILjava/lang/String;Z)I
 */
GAMS_Export jint JNICALL 
  Java_com_gams_platforms_VrepPlatform_jni_1addModelToEnvironment
  (JNIEnv *, jobject, jint, jstring, jboolean);

/*
 * Class:     com_gams_platforms_VrepPlatform
 * Method:    jni_getVrepPosition
 * Signature: (II)J
 */
GAMS_Export jlong JNICALL 
  Java_com_gams_platforms_VrepPlatform_jni_1getVrepPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_gams_platforms_VrepPlatform
 * Method:    jni_setVrepPosition
 * Signature: (IIJ)V
 */
GAMS_Export void JNICALL 
  Java_com_gams_platforms_VrepPlatform_jni_1setVrepPosition
  (JNIEnv *, jobject, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
