/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gams_algorithms_BaseAlgorithm */

#ifndef _Included_com_gams_algorithms_BaseAlgorithm
#define _Included_com_gams_algorithms_BaseAlgorithm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gams_algorithms_BaseAlgorithm
 * Method:    jni_Base
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_gams_algorithms_BaseAlgorithm_jni_1Base
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_gams_algorithms_BaseAlgorithm
 * Method:    jni_getKnowledgeBase
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_gams_algorithms_BaseAlgorithm_jni_1getKnowledgeBase
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_algorithms_BaseAlgorithm
 * Method:    jni_getSelf
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_gams_algorithms_BaseAlgorithm_jni_1getSelf
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_algorithms_BaseAlgorithm
 * Method:    jni_getPlatformObject
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_gams_algorithms_BaseAlgorithm_jni_1getPlatformObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_algorithms_BaseAlgorithm
 * Method:    jni_getAlgorithmStatus
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_gams_algorithms_BaseAlgorithm_jni_1getAlgorithmStatus
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
