/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gams_utility_Logging */

#ifndef _Included_com_gams_utility_Logging
#define _Included_com_gams_utility_Logging
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gams_utility_Logging
 * Method:    jni_set_level
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_gams_utility_Logging_jni_1set_1level
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gams_utility_Logging
 * Method:    jni_get_level
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gams_utility_Logging_jni_1get_1level
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
