/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "gams/GAMS_Export.h"
/* Header for class com_gams_platforms_VrepUavPlatform */

#ifndef _Included_com_gams_platforms_VrepUavPlatform
#define _Included_com_gams_platforms_VrepUavPlatform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gams_platforms_VrepUavPlatform
 * Method:    jni_getTargetHandle
 * Signature: (II)I
 */
GAMS_Export jint JNICALL 
  Java_com_gams_platforms_VrepUavPlatform_jni_1getTargetHandle
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
