/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gams_controllers_BaseController */

#ifndef _Included_com_gams_controllers_BaseController
#define _Included_com_gams_controllers_BaseController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gams_controllers_BaseController
 * Method:    jni_BaseControllerFromKb
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_gams_controllers_BaseController_jni_1BaseControllerFromKb
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_controllers_BaseController
 * Method:    jni_BaseController
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_gams_controllers_BaseController_jni_1BaseController
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_controllers_BaseController
 * Method:    jni_freeBaseController
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gams_controllers_BaseController_jni_1freeBaseController
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gams_controllers_BaseController
 * Method:    jni_toString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gams_controllers_BaseController_jni_1toString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_controllers_BaseController
 * Method:    jni_analyze
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_gams_controllers_BaseController_jni_1analyze
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_controllers_BaseController
 * Method:    jni_execute
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_gams_controllers_BaseController_jni_1execute
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_controllers_BaseController
 * Method:    jni_initAccent
 * Signature: (JLjava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_com_gams_controllers_BaseController_jni_1initAccent
  (JNIEnv *, jobject, jlong, jstring, jlongArray);

/*
 * Class:     com_gams_controllers_BaseController
 * Method:    jni_initAlgorithm
 * Signature: (JLjava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_com_gams_controllers_BaseController_jni_1initAlgorithm
  (JNIEnv *, jobject, jlong, jstring, jlongArray);

/*
 * Class:     com_gams_controllers_BaseController
 * Method:    jni_initPlatform
 * Signature: (JLjava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_com_gams_controllers_BaseController_jni_1initPlatform
  (JNIEnv *, jobject, jlong, jstring, jlongArray);

/*
 * Class:     com_gams_controllers_BaseController
 * Method:    jni_initVars
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_gams_controllers_BaseController_jni_1initVars
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_gams_controllers_BaseController
 * Method:    jni_initVarsAlgorithm
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_gams_controllers_BaseController_jni_1initVarsAlgorithm
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_gams_controllers_BaseController
 * Method:    jni_initVarsPlatform
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_gams_controllers_BaseController_jni_1initVarsPlatform
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_gams_controllers_BaseController
 * Method:    jni_monitor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_gams_controllers_BaseController_jni_1monitor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_controllers_BaseController
 * Method:    jni_plan
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_gams_controllers_BaseController_jni_1plan
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gams_controllers_BaseController
 * Method:    jni_run
 * Signature: (JDD)J
 */
JNIEXPORT jlong JNICALL Java_com_gams_controllers_BaseController_jni_1run
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     com_gams_controllers_BaseController
 * Method:    jni_systemAnalyze
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_gams_controllers_BaseController_jni_1systemAnalyze
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
